### ISSUE TITLE
イベントコマンド「注釈」の埋め込み

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [yktsr/Text2Frame-MV#12]
以下の記法でツクールのイベントコマンド「注釈」(Comment)を入れる記法
```
<comment>
  この辺でＢＧＭを変える
</comment>
```

### 別記法(2018/9/30追記)
```
<CO>
この辺でＢＧＭを変える 
</CO>
```
と
```
<注釈>
この辺でＢＧＭを変える
</注釈>
```
にする。

**Comment by HidetoshiKawaguchi** [comment]
devブランチにおいて、以下の修正をお願いします。
- <comment: ほげほげ>という記法ではなｋ，上述した仕様にする。注釈コマンドは複数行書けるので。
- 日本語記法は<コメント>ではなくて<注釈>にしましょう。日本語版ツクールMVの書き方に合わせます。

**Comment by yktsr** [comment]
commit e137abca4f61133adeae61731d19c35a776ba318
