### ISSUE TITLE
変数制御タグの実装

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [yktsr/Text2Frame-MV#35]
## 概要
変数制御を行うイベントコマンドを埋め込むための機能。
記法は
```
<オペコード: 第一オペランド, 第二オペランド>
```
オペコード: 代入, 加算, 減算, 乗算, 除算, 剰余のいずれかのオペレーションを表す
第一オペランド: オペレーション後の数値を入れる変数のID. 単一変数もしくは変数の範囲を表す。
第二オペランド: 演算される値を示す。定数, 変数ID, 乱数, ゲームデータ, スクリプトのいずれか

## 具体例
イメージをつかむためにいくつか具体例を示しておく。例ごとに3通りの記法を示しており、すべて同じイベントコマンドが組み込まれる
- 例1: 変数1に定数2を代入:
  - `<Set: 1, 2>`
  - `<=: 1, 2>`
  - `<代入: 1, 2>`
- 例2: 変数1-10(範囲指定)に変数3を加算:
  - `<Add: 1-10, variable[3]>`
  - `<+: 1-10, v[3]>`
  - `<加算: 1-10, 変数[3]>`
- 例3: 変数1に50から100の乱数を減算:
  - `<Sub: 1, random[50][100]>`
  - `<-: 1, r[50][100]>`
  - `<減算: 1, 乱数[50][100]>`
- 例4: 変数1にゲームデータのアクター2のレベルを乗算:
  - `<Mul: 1, gamedata[actor][2][level]>`
  - `<*: 1, gd[actor][2][level]>`
  - `<乗算: 1, ゲームデータ[アクター][2][レベル>`
- 例5 変数1にゲームデータのパーティ人数の剰余を代入:
  - `<Mod: 1, gamedata[PartyMembers]> `
  - `<%: 1, gd[PartyMembers]> `
  - `<剰余 1, ゲームデータ[パーティ人数]> `
- 例6: 変数1にスクリプト"$gameVariables.value(1)"を除算:
  - `<Div: 1, script[$gameVariables.value(1)]>`
  - `</: 1, sc[$gameVariables.value(1)]>`
  - `<除算: 1, スクリプト[$gameVariables.value(1)]>`

## オペコード
オペコードは代入, 加算, 減算, 乗算, 除算, 剰余のいずれかを以下の記法で表す。
なお、大文字小文字は区別しないものとする。
- 代入: `Set`, `=`, `代入` 
- 加算: `Add`, `+`, `加算` 
- 減算: `Sub`, `-`, `減算` 
- 乗算: `Mul`, `*`, `乗算` 
- 除算: `Div`, `/`, `除算` 
- 剰余: `Mod`, `%`, `剰余` 

## 第一オペランド
オペレーション後の数値を入れる変数のID. 単一変数もしくは変数の範囲を表す。
- 単一の変数: IDを示す整数。例えば変数10に操作したい場合は 10 が入る。
  - (例)変数10の場合: `10`
- 範囲: -(ハイフン記号)で２つの整数を結合する。
  - (例)変数10~100の場合 `10-100`

## 第二オペランド
演算される値を示す。定数, 変数ID, 乱数, ゲームデータ, スクリプトのいずれか。
カギ括弧で第二オペランドのパラメータを指定することができる。

### 定数
数値(整数)を直接記入する。
- (例) 定数20の場合: `20`

### 変数ID
variable[ID]という記法。IDには変数IDを示す整数値を入れる。
`variable`は、
- `v`
- `変数`

でも同じとする。
変数10を指定する場合の例は

- `variable[10]`
- `v[10]`  (省略形)
- `変数[10]`

である。

### 乱数
randome[下限値][上限値]で記述する。
`random`は
- `r`
- `乱数`

でも同じとする。
下限値50, 上限値100の範囲内での一様乱数の例は
- `random[50][100]`
- `r[50][100]`
- `乱数[50][100]`

である。

### ゲームデータ
GameData[種類][引数1][引数2]で記述する。引数1,引数2は無い場合もある。
`GameData`は
- `gd`
- `ゲームデータ`

でも同じとする。
以下、種類毎に細かく記法を記載する。

#### アイテム
GameData[item][アイテムID] と記述する。
- 記号: `item`,`アイテム`
- (例) アイテムIDが3のアイテム所持数:
  - `GameData[item][3]`
  - `GameData[アイテム][3]`

#### 武器
GameData[weapon][武器ID]と記述する。
- 記号: `weapon`,`武器`
- (例) 武器IDが4の武器所持数:
  - `GameData[weapon][4]`
  - `GameData[武器][4]`

#### 防具
GameData[weaponfdarmor][防具ID]と記述する。
- 記号: `armor`, `防具`
- (例) 防具IDが5の防具所持数:
  - `GameData[armor][5]`
  - `GameData[防具][5]`

#### アクター
アクターはアクターIDを指定して、そのアクターの何らかの値(能力値等)を参照する。
GameData[Actor][アクターID][能力値]と記述する。
- 記号: `actor`, `アクター`

第一引数のアクターIDは整数値で指定する。
更に、第二引数で以下のいずれかを指定する。
- レベル: `level`, `レベル`
- 経験値: `exp`, `経験値`
- HP: `hp`, `HP`
- MP: `mp`, `mp`
- 最大HP: `MaxHp`, `最大HP`
- 最大MP: `MaxMp`, `最大MP`
- 攻撃力: `attack`, `攻撃力`
- 防御力: `defense`, `防御力`
- 魔法攻撃力: `m.attack`, `魔法攻撃力`
- 魔法防御力: `m.defense`, `魔法防御力`
- 敏捷性: `agility`, `敏捷性`
- 運: `luck`, `運`

例えば、アクターID4のアクターの魔法攻撃力を参照する場合は
- `gamedata[actor][4][m.attack]`
- `gamedata[アクター][4][魔法攻撃力]`

となる。

#### エネミー
エネミーは戦闘中のエネミーIDを指定して、そのエネミーの何らかの値(能力値等)を参照する。
GameData[enemy][エネミーID][能力値]と記述する。
- 記号: `enemy`, `エネミー`
第一引数のエネミーIDは整数値で指定する。
更に、第二引数で以下のいずれかを指定する。(アクターからレベルと経験値がなくなっている）
- HP: `hp`, `HP`
- MP: `mp`, `mp`
- 最大HP: `MaxHp`, `最大HP`
- 最大MP: `MaxMp`, `最大MP`
- 攻撃力: `attack`, `攻撃力`
- 防御力: `defense`, `防御力`
- 魔法攻撃力: `m.attack`, `魔法攻撃力`
- 魔法防御力: `m.defense`, `魔法防御力`
- 敏捷性: `agility`, `敏捷性`
- 運: `luck`, `運`

例えば、エネミーID5のアクターの攻撃力を参照する場合は
- `gamedata[enemy][5][attack]`
- `gamedata[エネミー][5][攻撃力]`

となる。

#### キャラクター
キャラクターは、イベントなどのキャラクターの座標等の値を参照する。
GameData[character][イベントの指定][参照したい値]と記述する。
- 記号: `character`, `キャラクター`

第一引数ではイベントの指定を行う。以下のいずれかの記号を用いる
- プレイヤー: `player`, `プレイヤー`
- このイベント: `ThisEvent`, `このイベント`
- イベントID指定: `1`, `2`,... (整数値で指定)

更に、第二引数で以下のいずれかを指定する。
- マップX座標: `MapX`, `マップX`
- マップY座標: `MapY`, `マップy`
- 方向: `direction`, `方向`
- 画面X座標: `ScreenX`, `画面X`
- 画面Y座標: `ScreenY`, `画面X`

以下に例を示す。
- 例1: プレイヤーのX座標
  - `gamedata[character][player][MapX]`
  - `gamedata[キャラクター][プレイヤー][画面X]`
- 例2: このイベントのY座標
  - `gamedata[character][ThisEvent][MapY]`
  - `gamedata[キャラクター][このイベント][画面Y]`
- 例3: ID3のイベントの方向
  - `gamedata[character][3][direction]`
  - `gamedata[キャラクター][3][方向]`

#### パーティ
パーティメンバーの並び順を指定して、そのアクターのIDを参照する。
GameData[party][並び順]と記述する。
記号: `party`, `パーティ`
第一引数は整数で指定する。
例えば、パーティの先頭のアクターIDを参照する場合は
- `gamedata[party][1]`
- `gamedata[パーティ][1]`

#### その他
その他では、種類を記号で示すのみで、第一引数、第二引数は使わない。
GameData[その他の種類]と記述する。
その他の種類は以下の通りである。
- パーティ人数: `PartyMembers`, `パーティ人数`
- 所持金: `gold`, `所持金`,
- 歩数: `steps`, `歩数`
- プレイ時間: `PlayTime`, `プレイ時間`
- タイマー: `timer`, `タイマー`
- セーブ回数: `SaveCount`, `セーブ回数`
- 戦闘回数: `BattleCount`, `戦闘回数`
- 勝利回数: `WinCount`, `勝利回数`
- 逃走回数: `EscapeCount`, `逃走回数`

例えばパーティ人数の場合は
- `gamedata[PartyMembers]`
- `gamedata[パーティ人数]`

となる。

### スクリプト
script[内容(文字列)]と記述する。
`script`は
- `sc`
- `スクリプト`

でも同じものとする。
`"涼風" + $dataActors[1].name;`というスクリプトを示す場合は
- `script["涼風" + $dataActors[1].name;]`
- `sc["涼風" + $dataActors[1].name;]`
- `スクリプト["涼風" + $dataActors[1].name;]`

となる。

## 備考
タグの文字列(Addやvariable)などの大文字や小文字の区別はしないものとする。

**Comment by yktsr** [comment]
Close #32

**Comment by HidetoshiKawaguchi** [comment]
devブランチにテストケースいれました。
数が多いので、分割してtest/35-control_variablesディレクトリの中に入れてます。
