### ISSUE TITLE
スクリプトの埋め込み

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [yktsr/Text2Frame-MV#5]
# 概要
スクリプトコマンドをテキストから入力する機能。
以下の<Script> と</Script> のタグで挟んだテキストは、イベントコマンド「スクリプト」として組み込まれる。
例えば以下の通り。
```
<Script>
var a = 1;
var b = 2;    
</Script>
```
# 気になる点
ツクールMVのエディタ上では12行までしか打てないが果たして・・・？

# 別記法(2018/9/30追記)
別記法は
```
<SC>
var a = 1;
var b = 2;    
</SC>
```
と
```
<スクリプト>
var a = 1;
var b = 2;    
</スクリプト
```
にしましょう。

**Comment by yktsr** [comment]
簡単には改行を削除して一行にすればよいですが，複数行に改行された方が...よいですね

**Comment by HidetoshiKawaguchi** [comment]
ごめん、改行がうまくいってなかった。

**Comment by HidetoshiKawaguchi** [comment]
複数行に改行してくれたほうがいいですね。空行いれたくなるときありますから。

**Comment by yktsr** [comment]
commit 70f770eef6152c2cb97ad61893ec04bbbcb0b57d
