### ISSUE TITLE
変数操作とスイッチ操作の番号指定のバグ

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [yktsr/Text2Frame-MV#83]
変数操作とスイッチ操作の番号指定を二桁にすると、範囲指定での代入となってしまう。
例
```
<Switch: 10, OFF>
<Set: 10, 11>
```
本来、スイッチ10をOFFにする処理と、変数10に11を代入する処理となるのだが、なぜか範囲指定で1-0となる。

**Comment by yktsr** [comment]
報告ありがとうございます！
https://twitter.com/marupon_dou/status/1620460136585379840?s=20&t=fUqsm3-dDGlTTlOxrVvu6w
